- name: Configure Join Commands on Control Node
  hosts: control
  become: true
  vars_files:
    - vars.yml
  tasks:
    - name: Retrieve Join Command
      ansible.builtin.command: kubeadm token create --print-join-command
      register: join_command_raw
      changed_when: join_command_raw.rc == 0

    - name: Set Join Command
      ansible.builtin.set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"

- name: Join Worker Nodes
  hosts: workers
  vars_files:
    - vars.yml
  become: true
  tasks:
    - name: Enable TCP port 6443 (On Control) is able to connect from Worker
      ansible.builtin.wait_for:
        host: "{{ control_host }}"
        port: 6443
        timeout: 1

    - name: Join worker to cluster # if run is limited to worker nodes, this will fail
      ansible.builtin.shell: "{{ hostvars[(lookup('vars', 'control_host'))].join_command }} >> node_joined.log"
      args:
        chdir: "/home/{{ username }}"
        creates: node_joined.log
